INSERT INTO runners (id, name) VALUES (1, 'Lamont Marcell Jacobs');
INSERT INTO runners (id, name) VALUES (2, 'Fred Kerley');
INSERT INTO runners (id, name) VALUES (3, 'Andre De Grasse');
INSERT INTO runners (id, name) VALUES (4, 'Akani Simbine');
INSERT INTO runners (id, name) VALUES (5, 'Ronnie Baker');
INSERT INTO runners (id, name) VALUES (6, 'Bingtian Su');
INSERT INTO runners (id, name) VALUES (7, 'Enoch Adegoke');
INSERT INTO runners (id, name) VALUES (8, 'Zharnel Hughes');
INSERT INTO runners (id, name) VALUES (9, 'Ferdinand Omanyala Omurwa');
INSERT INTO runners (id, name) VALUES (10, 'Trayvon Bromell');
INSERT INTO runners (id, name) VALUES (11, 'Gift Leotlela');
INSERT INTO runners (id, name) VALUES (12, 'Oblique Seville');
INSERT INTO runners (id, name) VALUES (13, 'Rohan Browning');
INSERT INTO runners (id, name) VALUES (14, 'Shaun Maswanganyi');
INSERT INTO runners (id, name) VALUES (15, 'Chijindu Ujah');
INSERT INTO runners (id, name) VALUES (16, 'Jimmy Vicaut');
INSERT INTO runners (id, name) VALUES (17, 'Jason Rogers');
INSERT INTO runners (id, name) VALUES (18, 'Yohan Blake');
INSERT INTO runners (id, name) VALUES (19, 'Filippo Tortu');
INSERT INTO runners (id, name) VALUES (20, 'Femi Ogunode');
INSERT INTO runners (id, name) VALUES (21, 'Arthur Cisse');
INSERT INTO runners (id, name) VALUES (22, 'Usheoritse Itsekiri');
INSERT INTO runners (id, name) VALUES (23, 'Paulo Andre Camilo');
INSERT INTO runners (id, name) VALUES (24, 'Reece Prescod');
INSERT INTO runners (id, name) VALUES (25, 'Benjamin Azamati-Kwaku');
INSERT INTO runners (id, name) VALUES (26, 'Ryota Yamagata');
INSERT INTO runners (id, name) VALUES (27, 'Zhenye Xie');
INSERT INTO runners (id, name) VALUES (28, 'Zhiqiang Wu');
INSERT INTO runners (id, name) VALUES (29, 'Hassan Taftian');
INSERT INTO runners (id, name) VALUES (30, 'Kojo Musah');
INSERT INTO runners (id, name) VALUES (31, 'Chun-Han Yang');
INSERT INTO runners (id, name) VALUES (32, 'Yuki Koike');
INSERT INTO runners (id, name) VALUES (33, 'Shuhei Tada');
INSERT INTO runners (id, name) VALUES (34, 'Rodrigo Do Nascimento');
INSERT INTO runners (id, name) VALUES (35, 'Emmanuel Matadi');
INSERT INTO runners (id, name) VALUES (36, 'Jak Ali Harvey');
INSERT INTO runners (id, name) VALUES (37, 'Cejhae Greene');
INSERT INTO runners (id, name) VALUES (38, 'Felipe Bardi');
INSERT INTO runners (id, name) VALUES (39, 'Lalu Muhammad Zohri');
INSERT INTO runners (id, name) VALUES (40, 'Silvan Wicki');
INSERT INTO runners (id, name) VALUES (41, 'Barakat Al Harthi');
INSERT INTO runners (id, name) VALUES (42, 'Yupun Abeykoon Mudiyanselage');
INSERT INTO runners (id, name) VALUES (43, 'Ebrima Camara');
INSERT INTO runners (id, name) VALUES (44, 'Samson Colebrooke');
INSERT INTO runners (id, name) VALUES (45, 'Carlos Nascimento');
INSERT INTO runners (id, name) VALUES (46, 'Jan Volko');
INSERT INTO runners (id, name) VALUES (47, 'Dorian Keletela');
INSERT INTO runners (id, name) VALUES (48, 'Emanuel Archibald');
INSERT INTO runners (id, name) VALUES (49, 'Kemar Hyman');
INSERT INTO runners (id, name) VALUES (50, 'Ngoni Makusha');
INSERT INTO runners (id, name) VALUES (51, 'Gavin Smellie');
INSERT INTO runners (id, name) VALUES (52, 'Bismark Boateng');
INSERT INTO runners (id, name) VALUES (53, 'Emre Zafer Barnes');
INSERT INTO runners (id, name) VALUES (54, 'Mohamed Alhammadi');
INSERT INTO runners (id, name) VALUES (55, 'Yeykell Eliuth Romero');
INSERT INTO runners (id, name) VALUES (56, 'Ratu Banuve Tabakaucoro');
INSERT INTO runners (id, name) VALUES (57, 'Guy Maganga Gorra');
INSERT INTO runners (id, name) VALUES (58, 'Oliver Mwimba');
INSERT INTO runners (id, name) VALUES (59, 'Mario Burke');
INSERT INTO runners (id, name) VALUES (60, 'Fabrice Dabla');
INSERT INTO runners (id, name) VALUES (61, 'Divine Oduduru');
INSERT INTO runners (id, name) VALUES (62, 'Tyquendo Tracey');
INSERT INTO runners (id, name) VALUES (63, 'Bruno Rojas');
INSERT INTO runners (id, name) VALUES (64, 'Ildar Akhmadiev');
INSERT INTO runners (id, name) VALUES (65, 'Didier Kiki');
INSERT INTO runners (id, name) VALUES (66, 'Hassan Saaid');
INSERT INTO runners (id, name) VALUES (67, 'Badamassi Saguirou');
INSERT INTO runners (id, name) VALUES (68, 'Shaun Gill');
INSERT INTO runners (id, name) VALUES (69, 'Jonah Harris');
INSERT INTO runners (id, name) VALUES (70, 'Sokong Pen');
INSERT INTO runners (id, name) VALUES (71, 'Sha Mahmood Noor Zahi');
INSERT INTO runners (id, name) VALUES (72, 'Ronald Lawrence Fotofili');
INSERT INTO runners (id, name) VALUES (73, 'Lataisi Mwea');
INSERT INTO runners (id, name) VALUES (74, 'Scott James Fiti');
INSERT INTO runners (id, name) VALUES (75, 'Nathan Ikon Crumpton');
INSERT INTO runners (id, name) VALUES (76, 'Seco Camara');
INSERT INTO runners (id, name) VALUES (77, 'Adrian Justin Jimena Ililau');
INSERT INTO runners (id, name) VALUES (78, 'Karalo Hepoiteloto Maibuca');
INSERT INTO runners (id, name) VALUES (79, 'Aveni Miguel');

